# Generated by Django 4.1.7 on 2023-06-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcategory_comment_post_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date Created'),
        ),
    ]
